# Config file for automatic testing at travis-ci.org
language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
python: 3.5
install:
  - pip install tox
script: tox
services:
  - elasticsearch
  - mongodb
before_script:
  - travis_retry curl -XDELETE 'http://localhost:9200/ramses_starter/'
  - mongo ramses_starter --eval 'db.dropDatabase();'
